apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    id: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kanba"
