apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  storageClassName: manual
  selector:
    matchLabels:
      id: postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi 
